# Iris

## 1. Business Understanding
- What is the problem?
- What do we want to achieve?

## 2. Data Understanding

### Import Libraries

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Load Data

In [11]:
df = pd.read_csv("iris.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### Basic Information

In [12]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

## 3. Data Preparation

### Check Missing Values

In [13]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

### Clean Data

In [17]:
df = df.dropna()

## 4. Modeling

In [15]:
# Create your model here

# Example:
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LinearRegression

## 5. Evaluation

In [16]:
# Check how well the model performs

# Example:
# model.score(X_test, y_test)

## 6. Deployment / Conclusion

### Results
- What did we find?
- How accurate was the model?
- Did we solve the original problem?

### Conclusion
Write a short conclusion here.